### ISSUE TITLE
Deleted layer not removed from /Logical/Layers

### ISSUE THREAD

**Issue by helderbetiol** [ditrit/OGrEE-Core#315]
After deleting a layer with (for example: ` -/Logical/Layers/test`), if we use `ls /Logical/Layers`, we can still see the removed layer.

**Comment by Barbozafab** [comment]
I suppose the problem is a little deeper than what we previously thought. As far as I've been able to verify, **_anything_** removed with `-[slug]` is still listed when `ls` is called, not just layers. On the other hand, the removed object is not returned when `get` is called.

**Comment by Barbozafab** [comment]
This bug was caused by three different things: 

- `Logical/Layers` objects are cached, but the only criterion for checking if it were up-to-date was a timeout of 10 minutes. I modified the `DeleteObj` logic to unset the `IsCached` value of `/Logical/Layers`, so when `ls` is called, a new `GET` is performed and deleted layers are not shown. After an `ls` is called, `IsCached` is set back to `true`.

- `FillUrlTree` is responsible for `GET`ting and updating the children for most of the hierarchy. The function used to reset and refill all of the children's children lists, but did not do so for the original node's children list. This meant that all deleted children would still be listed after an `ls` call until `ls` was called in a higher hierarchy level. I modified this function to also reset and refill the original node's children list, thus eliminating deleted children from the original node's children list. 

- `FillWithMap` is similar to `FillUrlTree`, being responsible for updating the children list of a node with the information received from a `GET` call for some of the hierarchy. The function used to take into account solely the `GET` response for verifying if the children list should be updated, causing children to still be listed by an `ls` call.  I modified this function to reset the original node's children list before refilling it (if necessary) and returning, therefore eliminating deleted children from the original node's children list.
