### ISSUE TITLE
3D disconnect command for the CLI

### ISSUE THREAD

**Issue by helderbetiol** [ditrit/OGrEE-Core#325]
Add a new command to the CLI that allows it to disconnect from the 3D client (`disconnect3d`).

**Comment by Barbozafab** [comment]
I've added the new command `disconnect3d`. When called, the command properly disconnects the 3D from the CLI, but:

1) The 3D window is not closed;

2) The 3D window continues to say "Connected to [TenantName]";

3) If `connect3d` is called, everything looks fine on the CLI side, but the 3D is not updated and nothing happens when `draw` or some other function is called;

4) For the 3D to work again, the window has to be manually closed and reopened. 

Worth noting this is the same behaviour as when the CLI is closed but the 3D is not: the 3D window remains open and saying it's connected; when a new CLI is opened, it connects to the 3D but nothing happens when a function is called (besides the `disconnect3d`).

If `disconnect3d` is called and the CLI is not connected to the 3D, nothing happens. 

Is this the intended behaviour for this new command? Is there a way of sending a message to the 3D and letting it know that the connection was terminated? I suppose this would have to be done on the 3D side.

**Comment by Barbozafab** [comment]
Update! After calling `disconnect3d`, the 3D client now correctly states that it is no longer connect, and is ready to accept a new connection.
