### ISSUE TITLE
Refactor old commands: getu, getslot, hc

### ISSUE THREAD

**Issue by helderbetiol** [ditrit/OGrEE-Core#445]
Some old commands are not in the documentation and are not working properly. We should decide to fix them or to remove them if they are not useful. Here are the ones identified so far:

- getu
- getslot
- hc

**Comment by hchybz** [comment]
`getu` could  be suppressed because it could be aliased/ replaced  by 'get RACK:HEIGHT` as soon as we will have  `get OBJECT:ATTRIBUTE`

`hc` : WTF ? can't remember that one 

`getslot`: same as getu or `ls` with advanced filtering

**Comment by Cedrok** [comment]
- `getu` is getting a device with asked posU (It is actually wrongly implemented and refers to the rack height.. This should be fixed)
- `getslot` is getting a device placed at asked slot (since slot is an array, it means one of the slots is the asked one).
Both can be done with a `ls` with filters, but I think keeping these simple aliases is a good idea
- `hc` displays an object's hierarchy in JSON format, but doesn't work for now. This could be useful if we can output the result in a text file ?
